version: '3'
services:

  #PHP with APACHE
  php_apache:
    container_name: php_8.2_apache_container
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - C:\apache_docker:/var/www/html
    networks:
      - apache_network
    depends_on:
      - mysql

  #MYSQL
  mysql:
    image: mysql:8.1.0
    container_name: mysql_8.1.0_container
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: apache_username
      MYSQL_PASSWORD: apache_password
    ports:
      - "3306:3306"
    volumes:
      - C:\apache_docker\mysql:/var/lib/mysql
    networks:
      - apache_network

  #REDIS
  redis:
    image: redis:7.2.1
    container_name: redis_7.2.1_container
    #restart: always
    ports:
      - 6379:6379
    networks:
      - apache_network


  #PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    #restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - apache_network      


networks:
  apache_network: